// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"mall/api/product/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/product/:product_id",
				Handler: GetProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/create",
				Handler: CreateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/product/delete",
				Handler: DeleteProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/product/update",
				Handler: UpdateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/products",
				Handler: ListProductsHandler(serverCtx),
			},
		},
	)
}
