// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"mall/api/api/cart/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cart/clear",
				Handler: ClearCartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cart/item/add",
				Handler: AddItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cart/item/remove",
				Handler: RemoveItemHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cart/items",
				Handler: ListItemsHandler(serverCtx),
			},
		},
	)
}
