// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"mall/api/order/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/get",
				Handler: GetOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/list",
				Handler: ListOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/status/update",
				Handler: UpdateOrderStatusHandler(serverCtx),
			},
		},
	)
}
