// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type Empty struct {
}

type GetUserRequest struct {
	User_id string `path:"user_id"`
}

type ListUsersRequest struct {
	Page      int32 `form:"page"`
	Page_size int32 `form:"page_size"`
}

type ListUsersResponse struct {
	Users []UserInfo
	Total int32
}

type LoginRequest struct {
	Username string
	Password string
}

type LoginResponse struct {
	Token string
}

type RegisterRequest struct {
	Username string
	Password string
	Email    string
}

type RegisterResponse struct {
	User_id string
}

type UpdateUserRequest struct {
	User_id    string
	Email      string
	Phone      string
	Avatar_url string
}

type UserInfo struct {
	User_id    string
	Username   string
	Email      string
	Phone      string
	Avatar_url string
	Is_admin   bool
}
