// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AddItemRequest struct {
	User_id    string
	Product_id int64
	Quantity   int32
}

type CartItem struct {
	Product_id   int64
	Product_name string
	Quantity     int32
	Price        float32
	Image_url    string
}

type ClearCartRequest struct {
	User_id string
}

type Empty struct {
}

type ListItemsRequest struct {
	User_id string
}

type ListItemsResponse struct {
	Items []CartItem
}

type RemoveItemRequest struct {
	User_id    string
	Product_id int64
}
