// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type ProductBrief struct {
	Product_id int64
	Name       string
	Price      float32
	Image_url  string
}

type RecommendRequest struct {
	User_id string
	Limit   int32
}

type RecommendResponse struct {
	Products []ProductBrief
}
