// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CreateProductRequest struct {
	Name        string
	Description string
	Price       float32
	Stock       int32
	Images      []string
	Category_id int64
}

type DeleteProductRequest struct {
	Product_id int64
}

type Empty struct {
}

type GetProductRequest struct {
	Product_id int64
}

type ListProductsRequest struct {
	Page         int32
	Page_size    int32
	Keyword      string
	Category_ids []int64
}

type ListProductsResponse struct {
	Products []Product
	Total    int32
}

type Product struct {
	Product_id  int64
	Name        string
	Description string
	Price       float32
	Stock       int32
	Images      []string
	Category_id int64
}

type ProductBrief struct {
	Product_id int64
	Name       string
	Price      float32
	Image_url  string
}

type SearchRequest struct {
	Keyword   string
	Page      int32
	Page_size int32
}

type SearchResponse struct {
	Products []ProductBrief
	Total    int32
}

type SuggestionsRequest struct {
	Prefix string
	Limit  int32
}

type SuggestionsResponse struct {
	Suggestions []string
}

type UpdateProductRequest struct {
	Product_id  int64
	Name        string
	Description string
	Price       float32
	Stock       int32
	Images      []string
	Category_id int64
}
