// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreateProductRequest struct {
	Name        string
	Description string
	Price       float64
	Stock       int64
	ImageUrl    string
	CategoryId  int64
	IsAvailable bool
}

type DeleteProductRequest struct {
	ProductId int64
}

type Empty struct {
}

type GetProductRequest struct {
	ProductId int64
}

type ListProductsRequest struct {
	Page        int64   `form:"page" json:"page"`
	PageSize    int64   `form:"page_size" json:"page_size"`
	Keyword     string  `form:"keyword" json:"keyword"`
	CategoryIds []int64 `form:"category_ids" json:"category_ids"`
}

type ListProductsResponse struct {
	Products []Product
	Total    int64
}

type Product struct {
	ProductId   int64
	Name        string
	Description string
	Price       float64
	Stock       int64
	ImageUrl    string
	CategoryId  int64
	IsAvailable bool
	CreatedAt   string
	UpdatedAt   string
}

type UpdateProductRequest struct {
	ProductId   int64
	Name        string
	Description string
	Price       float64
	Stock       int64
	ImageUrl    string
	CategoryId  int64
	IsAvailable bool
}
