// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: product.proto

package server

import (
	"context"

	"mall/product/internal/logic"
	"mall/product/internal/svc"
	"mall/product/mall/product"
)

type ProductServiceServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServiceServer
}

func NewProductServiceServer(svcCtx *svc.ServiceContext) *ProductServiceServer {
	return &ProductServiceServer{
		svcCtx: svcCtx,
	}
}

// 商品列表
func (s *ProductServiceServer) ListProducts(ctx context.Context, in *product.ListProductsRequest) (*product.ListProductsResponse, error) {
	l := logic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}

// 获取商品详情
func (s *ProductServiceServer) GetProduct(ctx context.Context, in *product.GetProductRequest) (*product.Product, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

// 创建商品
func (s *ProductServiceServer) CreateProduct(ctx context.Context, in *product.CreateProductRequest) (*product.Product, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

// 更新商品
func (s *ProductServiceServer) UpdateProduct(ctx context.Context, in *product.UpdateProductRequest) (*product.Empty, error) {
	l := logic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

// 删除商品
func (s *ProductServiceServer) DeleteProduct(ctx context.Context, in *product.DeleteProductRequest) (*product.Empty, error) {
	l := logic.NewDeleteProductLogic(ctx, s.svcCtx)
	return l.DeleteProduct(in)
}

// 搜索提示词（联想词）
func (s *ProductServiceServer) SearchSuggestions(ctx context.Context, in *product.SuggestionsRequest) (*product.SuggestionsResponse, error) {
	l := logic.NewSearchSuggestionsLogic(ctx, s.svcCtx)
	return l.SearchSuggestions(in)
}

// 搜索商品
func (s *ProductServiceServer) SearchProducts(ctx context.Context, in *product.SearchRequest) (*product.SearchResponse, error) {
	l := logic.NewSearchProductsLogic(ctx, s.svcCtx)
	return l.SearchProducts(in)
}
