// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CreateOrderRequest struct {
	User_id        string
	Items          []OrderItem
	Address        string
	Payment_method string
}

type CreateOrderResponse struct {
	Order_id string
}

type Empty struct {
}

type GetOrderRequest struct {
	Order_id string
}

type ListOrdersRequest struct {
	User_id   string
	Page      int32
	Page_size int32
}

type ListOrdersResponse struct {
	Orders []OrderInfo
	Total  int32
}

type OrderInfo struct {
	Order_id       string
	User_id        string
	Items          []OrderItem
	Total_amount   float32
	Status         string
	Address        string
	Payment_method string
	Created_at     string
}

type OrderItem struct {
	Product_id int64
	Quantity   int32
	Price      float32
}

type UpdateOrderStatusRequest struct {
	Order_id string
	Status   string
}
