// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: recommend.proto

package server

import (
	"context"

	"mall/recommend/internal/logic"
	"mall/recommend/internal/svc"
	"mall/recommend/mall/recommend"
)

type RecommendServiceServer struct {
	svcCtx *svc.ServiceContext
	recommend.UnimplementedRecommendServiceServer
}

func NewRecommendServiceServer(svcCtx *svc.ServiceContext) *RecommendServiceServer {
	return &RecommendServiceServer{
		svcCtx: svcCtx,
	}
}

// 根据用户ID推荐商品列表
func (s *RecommendServiceServer) RecommendProducts(ctx context.Context, in *recommend.RecommendRequest) (*recommend.RecommendResponse, error) {
	l := logic.NewRecommendProductsLogic(ctx, s.svcCtx)
	return l.RecommendProducts(in)
}
